AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: Node.js 22 TypeScript Lambda Template

Globals:
  Function:
    Timeout: 30
    MemorySize: 256
    Runtime: nodejs22.x
    Architectures:
      - arm64

Resources:
  ExampleFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: dist/index.handler
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /hello
            Method: post
      Environment:
        Variables:
          NODE_ENV: production
      Policies:
        - AWSLambdaBasicExecutionRole

Outputs:
  ApiEndpoint:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello"
  FunctionName:
    Description: Lambda Function name
    Value: !Ref ExampleFunction 